language: node_js
node_js:
  - "0.10"
after_success:
  - ./node_modules/.bin/jscoverage index.js index-cov.js
  - MICROLOG_COV=1 NODE_ENV=test ./node_modules/.bin/mocha -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
